
[{
  "kind"=>"t1",
  "data"=>{
    "subreddit_id"=>"t5_2r0ij",
    "edited"=>false,
    "banned_by"=>nil,
    "removal_reason"=>nil,
    "link_id"=>"t3_5q4qmg",
    "link_author"=>"spez",
    "likes"=>nil,
    "replies"=>"",
    "user_reports"=>[],
    "saved"=>false,
    "id"=>"dcwe4m6",
    "gilded"=>0,
    "archived"=>false,
    "report_reasons"=>nil,
    "author"=>"spez",
    "parent_id"=>"t1_dcwceu5",
    "score"=>115,
    "approved_by"=>nil,
    "over_18"=>false,
    "controversiality"=>0,
    "body"=>"If Reddit could be killed, it'd be dead by now.",
    "link_title"=>"Out with 2016, in with 2017",
    "author_flair_css_class"=>nil,
    "downs"=>0,
    "body_html"=>"&lt;div class=...",
    "quarantine"=>false,
    "subreddit"=>"announcements",
    "name"=>"t1_dcwe4m6",
    "score_hidden"=>false,
    "stickied"=>false,
    "created"=>1485401335.0,
    "author_flair_text"=>nil,
    "link_url"=>"https://www.reddit....",
    "created_utc"=>1485372535.0,
    "distinguished"=>"admin",
    "mod_reports"=>[],
    "num_reports"=>nil,
    "ups"=>115}
},
{"kind"=>"t1", "data"=>{"subreddit_id"=>"t5_2r0ij", "edited"=>false, "banned_by"=>nil, "removal_reason"=>nil, "link_id"=>"t3_5q4qmg", "link_author"=>"spez", "likes"=>nil, "replies"=>"", "user_reports"=>[], "saved"=>false, "id"=>"dcwe4m6", "gilded"=>0, "archived"=>false, "report_reasons"=>nil, "author"=>"spez", "parent_id"=>"t1_dcwceu5", "score"=>115, "approved_by"=>nil, "over_18"=>false, "controversiality"=>0, "body"=>"If Reddit could be killed, it'd be dead by now.", "link_title"=>"Out with 2016, in with 2017", "author_flair_css_class"=>nil, "downs"=>0, "body_html"=>"&lt;div class=\"md\"&gt;&lt;p&gt;If Reddit could be killed, it&amp;#39;d be dead by now.&lt;/p&gt;\n&lt;/div&gt;", "quarantine"=>false, "subreddit"=>"announcements", "name"=>"t1_dcwe4m6", "score_hidden"=>false, "stickied"=>false, "created"=>1485401335.0, "author_flair_text"=>nil, "link_url"=>"https://www.reddit.com/r/announcements/comments/5q4qmg/out_with_2016_in_with_2017/", "created_utc"=>1485372535.0, "distinguished"=>"admin", "mod_reports"=>[], "num_reports"=>nil, "ups"=>115}}
]
